feat: add card homework lecture 2
Letto228/Angular-learnjs-200323 pull request #12
Opened 2023-03-29 01:17 UTC by KirillAsmanov

![image](https://user-images.githubusercontent.com/33131972/228401596-40b1eb0f-ebf1-4f19-8da6-35d0b85f6d7a.png)

2023-03-30 04:18 UTC, Letto228 requested changes
Привет!
Все круто, есть один комментарий/вопрос, посмотри, пожалуйста

2023-03-30 04:18 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.css
> +	background-image: url('https://material.angular.io/assets/img/examples/shiba1.jpg');
Тут статично иконка привязана, так и планировалось, или забыл убрать?
Почему спрашиваю: компонент карточки подразумевает отображение данных сущности карточки, соответсвенно статично отображаемых данных в шаблоне быть не должно, иначе для всех карточек будет одна и та же аватарка, и, согласись, выглядеть будет странновато, или, возможно, я идею не до конца понял)

В общем, буду ждать уточнения от тебя

2023-03-31 10:49 UTC, KirillAsmanov commented on src/app/pages/products-list/card/card.component.css
> +	background-image: url('https://material.angular.io/assets/img/examples/shiba1.jpg');
Действительно, забыл убрать)

2023-04-02 04:53 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.css
> +	background-image: url('https://material.angular.io/assets/img/examples/shiba1.jpg');
Принял)
Тогда апрув и закрываем МР

2023-04-02 04:54 UTC, Letto228 approved these changes

2023-04-02 04:54 UTC, closed without merging