feat: add card component
Letto228/Angular-learnjs-200323 pull request #14
Opened 2023-03-30 01:06 UTC by ilyaip

2023-03-30 04:31 UTC, Letto228 requested changes
Привет!
Хорошее решение, оставил пару не больших комментариев, посмотри, пожалуйста

2023-03-30 04:31 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.css
> +.example-header-image {
Класс нигде не используется, давай удалим

2023-03-30 04:31 UTC, Letto228 commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
Почему не стал создавать отдельный модуль под карточку?

2023-03-30 04:31 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +	<img mat-card-image src="{{ item.images[2].url }}" alt="Photo of a Shiba Inu" />
Почему тут решил интерполяцию использовать?

2023-03-30 04:31 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +			<mat-icon color="primary" aria-hidden="true" fontIcon="star"></mat-icon>
А давай сделаем, чтобы иконки звезд закрашивались согласно среднему рейтингу товара (`raiting` поле в модели карточки)? Т.е. если оценка 4 - закрашиваем 4 звезды, если 2.5 закрашиваем 2 звезды и т.д.

2023-03-30 08:06 UTC, ilyaip commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
я подумал что мелкий модуль, в котором будут использоваться только переиспользуемые ком-ты (вроде button или icon) и это не заслуживает отдельного модуля)

2023-03-30 08:09 UTC, ilyaip commented on src/app/pages/products-list/card/card.component.html
> +	<img mat-card-image src="{{ item.images[2].url }}" alt="Photo of a Shiba Inu" />
по идее меня устраивает что всегда будет подставляться строка с урлом

2023-04-02 05:07 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +	<img mat-card-image src="{{ item.images[2].url }}" alt="Photo of a Shiba Inu" />
Понял
Но тут вопрос касается не только тех части, но и хороших практик: семантически более удобно разделять привязки (для передачи данных в свойства) и интерполяцию (для вычисления контента страницы)

Т.к. все хорошие практики носят рекомендательный характер - оставляю конечное решение на твое усмотрение)

2023-04-02 05:16 UTC, Letto228 commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
Принял
Вижу, что вынес в отдельный модуль 👍, но сделал это до четверговой лекции, по этому хочу уточнить: остались ли вопросы/недопонимания/сметения по теме создания модулей для компонентов?

2023-04-02 05:18 UTC, Letto228 approved these changes
Огонь! - апрув

2023-04-02 05:18 UTC, closed without merging

2023-04-02 14:29 UTC, ilyaip commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
Нет, спасибо, еще доп почитал, все понял

2023-04-02 14:30 UTC, ilyaip commented on src/app/pages/products-list/card/card.component.html
> +	<img mat-card-image src="{{ item.images[2].url }}" alt="Photo of a Shiba Inu" />
Да, во время лекции еще уточняли, все понял