Домашнее задание по 2ой лекции
Letto228/Angular-learnjs-200323 pull request #15
Opened 2023-03-30 13:02 UTC by krasotun

2023-03-31 04:57 UTC, Letto228 requested changes
Привет!
Огонь, все выполнено лаконично. Один комментарий оставил по модулю, посмотри, пожалуйста. Буду ждать твоего ответа

2023-03-31 04:57 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +			<b>{{ item.price | currency : 'RUB' }}</b>
Бьешь на опережение, пайпы у нас впереди)

2023-03-31 04:57 UTC, Letto228 commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
Вопрос про модуль, почему не стал его создавать отдельно для компонента карточки?
Вчера на лекции это обсудили, как теперь считаешь, стоит ли его выделить в отдельный модуль?

2023-04-03 07:18 UTC, krasotun commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
ф выделю, но мне кажется это лишним - не совсем понял, зачем под каждый компонент отдельный модуль

2023-04-03 09:42 UTC, Letto228 commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
Я бы предложил это обсудить в таком случае, если есть желание: хочется поподробнее узнать твое мнение и рассмотреть пару кейсов, если твое мнение не поменяется, или поменяется мое, то будем писать без модуля такие кейсы
В любом случае, не стоит писать код вопреки своему мнению)

Напиши пожалуйста мне в дискорде, если хочешь обсудить, тогда там продолжим диалог

2023-04-03 09:43 UTC, Letto228 approved these changes
Увидел комментарий и по нему отписал, буду ждать твоего ответа.

По МР комментариев нет, все круто! - апрув

2023-04-03 09:43 UTC, closed without merging