feat: add card component
Letto228/Angular-learnjs-200323 pull request #17
Opened 2023-03-30 15:00 UTC by tsyk007

2023-03-31 05:10 UTC, Letto228 requested changes
Привет!
Хороший компонент получился 👍. Оставил один комментарий по модулю, посмотри, пожалуйста. Буду ждать твоего ответа

2023-03-31 05:10 UTC, Letto228 commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
Вопрос про модуль, почему не стал его создавать отдельно для компонента карточки?
Вчера на лекции это обсудили, как теперь считаешь, стоит ли его выделить в отдельный модуль?

2023-03-31 11:27 UTC, tsyk007 commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
да, теперь считаю, что стоит. Сделаю)

2023-04-02 05:26 UTC, Letto228 commented on src/app/pages/products-list/products-list.module.ts
> +	declarations: [ProductsListComponent, CardComponent],
Супер! Тогда жду коммита с изменениями (выделение отдельного модуля) и будем закрывать МР

2023-04-03 04:48 UTC, Letto228 approved these changes
Огонь!

2023-04-03 04:48 UTC, closed without merging