feat: lecture-3 dz. input and output
Letto228/Angular-learnjs-200323 pull request #21
Opened 2023-04-02 16:07 UTC by tsyk007

2023-04-03 10:18 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста. Буду ждать твоего ответа

2023-04-03 10:18 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +	@Input() product!: IProduct;
Почему не стал учитывать тот кейс, что могут прокинуть `undefined`?

2023-04-03 10:18 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +		<button mat-button (click)="productBuy.emit([$event, product])">Buy</button>
Почему решил прокинуть в Output `productBuy` событие клика, вместе с продуктом? И почему использовал для этого массив?

2023-04-03 14:51 UTC, tsyk007 commented on src/app/pages/products-list/card/card.component.ts
> +	@Input() product!: IProduct;
хотя в случае undefined лучше и не выводить вообще компонент

2023-04-04 04:20 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +	@Input() product!: IProduct;
Согласен, чуть позже мы к такой логике и придем)

2023-04-04 04:23 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.html
> +		<button mat-button (click)="productBuy.emit([$event, product])">Buy</button>
Да, все верно, лучше событие обрабатывать на уровне компонента. Если событие нужно на уровне родителя, то стоит подписаться на него на уровне родителя: в нашем случае можно было бы подписаться на событие клика на уровне products-list компонента

Но, если все таки специфика вынуждает в событии прикидывать набор данных (эвент тоже считаем за данные) то лучше использовать объект, он более читаемый

2023-04-04 04:27 UTC, Letto228 approved these changes
Cool - approve

2023-04-04 04:27 UTC, closed without merging