ДЗ Лекция 3, input/output
Letto228/Angular-learnjs-200323 pull request #27
Opened 2023-04-03 19:03 UTC by krasotun

2023-04-04 05:09 UTC, Letto228 requested changes
Привет!
В целом все good, но есть пару комментариев, посмотри, пожалуйста. Буду жать твоего ответа

2023-04-04 05:09 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> -		event.stopPropagation();
Потеряли остановку всплытия события клика, а она нам по прежнему нужна. Давай вернем данную функциональность

2023-04-04 05:09 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +	@Output() buyProduct = new EventEmitter<string>();
Возникает некий диссонанс, в дженерике указана строка `<string>`, но по факту эмит вызывается с типом `<void>`, то есть в нем не прокидываются никакие данные.
Давай сделаем так, чтобы в Output прокидывался `id` продукта, соответсвенно в типизации оставим `string`

2023-04-04 05:09 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.ts
> +		console.log('Купили');
Не плохо бы понимать еще, какой продукт купили. Давай доплним вывод в консоли `id` купленного товара

2023-04-04 08:01 UTC, krasotun commented on src/app/pages/products-list/card/card.component.ts
> +	@Output() buyProduct = new EventEmitter<string>();
Пофиксил

2023-04-06 06:30 UTC, Letto228 requested changes

2023-04-06 06:30 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +	@Output() buyProduct = new EventEmitter<string>();
Кажется, осталось так же, в дженерике указываем `string` (`EventEmitter<string>`), а по факту ничего в output не прокидываем `this.buyProduct.emit();`

Смотри, у нас output это механизм общения ребенка с родителем. Получается, логически, `buyProduct` output сообщает родителю, что был куплен продукт, соответсвенно, родителю нужно знать, какой именно продукт был куплен, т.е. нужен id купленного продукта, чтобы выполнить хоть какую то логику.
Вот и приходим к тому, что нам нужен Output, который сообщит родителю, что был куплен продукт с таким то id и в output эмитить событие мы должны с id

2023-04-06 08:41 UTC, Letto228 approved these changes
Супер 👍 - апрув

2023-04-06 08:41 UTC, closed without merging