feat: lecture-4 dz. popup
Letto228/Angular-learnjs-200323 pull request #32
Opened 2023-04-06 14:47 UTC by tsyk007

2023-04-07 05:36 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, в том числе есть претендент на баг, посмотри, пожалуйста. Буду ждать твоего ответа

2023-04-07 05:36 UTC, Letto228 commented on src/app/core/popup/popup.component.html
> +		<div>
Этот `div` не лишний? Выглядит странно 🤔

2023-04-07 05:36 UTC, Letto228 commented on src/app/core/popup/popup.component.ts
> +		if (this.template) {
Ты уже делаешь данную проверку выше `if (template.currentValue) {`, нет смысла проводить ее второй раз.
Предлагаю подумать в сторону ухода от метода и использовать `this.viewport.createEmbeddedView(this.template);` напрямую в `ngOnChanges`.

Скорее всего, при такой реализации TS будет ругаться на то, что `this.template` может быть `undefined`, но у нас есть пару инструментов, чтобы это решить:
1. `as`. Мы можем явно указать для TS, что `this.template` это `TemplateRef<any>`: `this.template as TemplateRef<any>`
2. Заменить `template.currentValue` на `this.template`. По сути `template.currentValue === this.template`, но из за того, что нет прямой проверки `this.template` TS не может понять, что внутри блока if у `this.template` отсутствует `undefined`, т.е. не может сузить набор типов. Если мы пропишем явную проверку, то все встанет на свои места и внутри if блока `this.template` будет иметь интерфейс только `TemplateRef<any>` (`this.template: TemplateRef<any>`)

2023-04-07 05:36 UTC, Letto228 commented on src/app/core/popup/popup.component.ts
> +		if (template.currentValue) {
Представь, а что если появится новый инпут (`context`), и он будет изменяться без изменения инпута `template`. Будет ли ошибка в методе `ngOnChanges` в таком случае?

2023-04-07 08:59 UTC, tsyk007 commented on src/app/core/popup/popup.component.html
> +		<div>
просто его использовал для контента окна, и при центрировании, чтобы элементы не центрировались друг относительно друга

2023-04-08 07:38 UTC, Letto228 commented on src/app/core/popup/popup.component.ts
> +		if (template.currentValue) {
> походу будет, template - undefined

Да, все верно, и из-за этого будет ошибка - `Uncaught TypeError: Cannot read properties of undefined (reading 'currentValue')`

2023-04-08 07:49 UTC, Letto228 requested changes
Огонь 🔥 , мне нравится) Оставил еще не большой комментарий по логике, посмотри, пожалуйста

2023-04-08 07:49 UTC, Letto228 commented on src/app/core/popup/popup.component.ts
> +			this.viewport.createEmbeddedView(this.template);
Давай еще немного раскрутим тему со вставкой шаблона.
Предположим, нам поочередно пришло 2 разных темплейта в ипут: сначала первый, а через 4 сек второй. Какое поведение ты ожидал бы?
Мне кажется, что при поучении нового шаблона, логично уничтожать view старого шаблона и создавать новый, т.е. нужно очистить контейнер view и только после этого создать новое.
В твоей реализации будет работать немного иначе: вставится созданное view по первому шаблону, а потом, поверх первого view вставится второе, созданное по второму полученому шаблону. Т.е. одновременно у тебя будет существовать 2 view - по одному на полученный шаблон, пока не придет `null` и не очистится весь контейнер. НО, возможно, ты так и подразумевал, хочется услышать твоего мнения

2023-04-09 12:08 UTC, tsyk007 commented on src/app/core/popup/popup.component.ts
> +			this.viewport.createEmbeddedView(this.template);
нет, так не хотел. Логичнее при любом изменении шаблона очищать viewport

2023-04-10 05:32 UTC, Letto228 approved these changes
Супер - апрув!

2023-04-10 05:32 UTC, closed without merging