Домашняя работа 5
Letto228/Angular-learnjs-200323 pull request #34
Opened 2023-04-09 11:16 UTC by Mu57Di3

feat: реализация директивы бесконечного скрола

Не уверен что корректно работает, но какой-то результат дает.

Орехов Алексей

2023-04-10 06:56 UTC, Letto228 requested changes
Нихао!
По логике отправке события почти супер, есть вопросик не большой по `offsetHeight` - оставил комментарий, и про подписку (`subscribe`) оставил комментарий, остальные комментарии косаются качества кода и хороших практик.
Посмотри, пожалуйста. Буду ждать фидбека

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +export enum LoadDorection {
Хорошей практикой считается выделять в отдельный файл - `load-dorection.enum.ts`. Так файл класса директивы станет более чистым, а enum будет более интуитивно шариться в друие фичи (по пути `.../load-dorection.enum.ts`, а не `.../scroll-with-loading.directive.ts`)

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +				if (target.scrollTop <= ScrollDelta) {
Не необходимая вложенность по if блокам, это считается плохой практикой. Попробуй объединить 2 if блока в один

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +				if (target.scrollTop <= ScrollDelta) {
Ниже такая же ситуация

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +	private root: any;
Давай вернем типизацию - во всем классе `any` заменим на валидные типы, которые реально будут храниться в данных свойствах. Использования `any` в таком контексте считается плохой практикой, в целом использование `any` в проекте нужно стараться свести в 0

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +	private scrollEvent: Observable<any>;
В таком случае свойство должно называться `scrollEvent$` - `$` добавляется согласно общим конвенциям комюнити

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +		this.scrollEvent.subscribe(({target}: any) => {
Подписка получается бесконечная, она не уничтожается, а это может иметь последствия, такие как утечка памяти и неожиданные сайд эффекты (но это не наш случай). Я бы рекомендовал использовать `HostBinding`, раз есть такая возможность, так директива будет выглядеть более привычно и чище в контексте Angular. Однако с твоим подходом тоже можно сделать интересно - использовать поток по скроллу для `Output`: `@Output() loadData: Observable<LoadDirection> = fromEvent(this.root, 'scroll').pipe(...)`; практика не обычная но не плохая!
Можно и твой вариант оставить, но тогда нужно подумать об отписке от потока при уничтожении директивы, чтобы себе проблем не нажить

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +					target.scrollTop + target.offsetHeight >=
Почему вычислял через `offsetHeight`?
<img width="666" alt="Снимок экрана 2023-04-10 в 09 52 24" src="https://user-images.githubusercontent.com/54375830/230844716-baeb6864-2d49-422d-8802-1698410c1a67.png">

2023-04-10 06:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +			this.lastScrollTop = target.scrollTop <= 0 ? 0 : target.scrollTop;
Почему такую проверку добавил? На мой взгляд достаточно просто сохранять позицию без проверок

2023-04-10 09:51 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +export enum LoadDorection {
Да вынес. Не фанат я горы файлов в 2-3 строки.

2023-04-10 09:53 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +				if (target.scrollTop <= ScrollDelta) {
В данном контексте разделение допустимо, упрощает понимание кода. Тут идет логическое разделение функции внешний if это определение направления скрола, второй это срабатывания порога. Такой же ответ к комментарию ниже.

2023-04-10 09:53 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +	private scrollEvent: Observable<any>;
был не в курсе.

2023-04-10 09:54 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +		this.scrollEvent.subscribe(({target}: any) => {
Да добавил отписку на метод ngOnDestroy

2023-04-10 09:54 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +					target.scrollTop + target.offsetHeight >=
при отсутствии падингов offsetHeight и clientHeight равноценны. На самом деле копипаста из моего старого кода.

2023-04-10 09:55 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +			this.lastScrollTop = target.scrollTop <= 0 ? 0 : target.scrollTop;
Упрощает проверку на скролл вверх, без нее есть проблемы в работе.

2023-04-11 04:08 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +				if (target.scrollTop <= ScrollDelta) {
Мне кажется, что через константы можно было бы не потерять в читаемости и использовать один if блок.
Но Гуд, аргумент засчитан

2023-04-11 04:10 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +			this.lastScrollTop = target.scrollTop <= 0 ? 0 : target.scrollTop;
А можешь чуть подробнее, пожалуйста, описать? Не совсем понимаю, почему проверка упрощается и какие есть проблемы без данной логики

2023-04-11 06:43 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +			this.lastScrollTop = target.scrollTop <= 0 ? 0 : target.scrollTop;
Да сейчас проверочка уже не актуальна. Копипаста из старого кода где scrollTop мог быть отрицательным.

2023-04-11 06:47 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +			this.lastScrollTop = target.scrollTop <= 0 ? 0 : target.scrollTop;
Глупая ошибка вобщем

2023-04-13 10:56 UTC, Letto228 requested changes
Оставил пару не больших комментариев, посмотри, пожалуйста

2023-04-13 10:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +		this.subInstance = this.scrollEvent$.subscribe(({target}: any) => {
Почему тут `scrollEvent$: Observable<any>;` и тут `{target}: any` решил оставить any?

2023-04-13 10:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +		this.root = element.nativeElement;
А на самом то деле, нужно ли тебе его сохранять? Я думаю, свойство `root` не нужно и его можно удалить

2023-04-13 10:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +const ScrollDelta = 100;
Почему с большой буквы? Код стайл такой?

2023-04-13 10:56 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +      console.log(target.scrollTop);
Давай `console.log` уберем, его все таки не должно в продовом коде быть

2023-04-13 14:16 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +		this.root = element.nativeElement;
да убрал действительно не нужная уже константа

2023-04-13 14:16 UTC, Mu57Di3 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +      console.log(target.scrollTop);
Даже время не хочу на это тратить

2023-04-15 09:42 UTC, Letto228 approved these changes
Гуд! - апрув

2023-04-15 09:42 UTC, closed without merging