Lecture 5 dz
Letto228/Angular-learnjs-200323 pull request #37
Opened 2023-04-10 00:09 UTC by tsyk007

2023-04-13 12:16 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев по чистоте кода и пару вопросов, посмотри, пожалуйста. Буду ждать фидбека

2023-04-13 12:16 UTC, Letto228 commented on src/app/shared/scroll-with-loading/load-direction.enum.ts
> +	before,
Я бы рекомендовал для свойств enum указать значения, чтобы придать им уникальности не только в типизации, но и в значении
```
export enum LoadDirection {
	Before = 'before',
	After = 'after',
}
```

2023-04-13 12:16 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +			scrollTop > this.lastScrollTop &&
Давай условие из if вынесем в константы с говорящим неймингом, чтобы повысить читаемость кода

2023-04-13 12:16 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +		this.lastScrollTop = scrollTop <= 0 ? 0 : scrollTop;
Почему тут такая проверка? Почему не просто `this.lastScrollTop = scrollTop;`?

2023-04-13 12:16 UTC, Letto228 commented on src/app/shared/scroll-with-loading/scroll-with-loading.directive.ts
> +			this.lastScrollHeightOnAfter = element.scrollHeight;
Имеет смысл при попадани в первый if, который означает загрузку данных сверху, выходить из функции, т.к. нет смысла проверять в таком случаи загрузку снизу (`scrollTop > this.lastScrollTop` и `scrollTop < this.lastScrollTop` - противоположные проверки, если один `true`, то другой будет `false`)

2023-04-13 16:29 UTC, tsyk007 commented
поправил

2023-04-15 09:49 UTC, Letto228 approved these changes
Огонь 🔥  - апрув!

2023-04-15 09:49 UTC, closed without merging