feat: lecture-6 dz. pagination
Letto228/Angular-learnjs-200323 pull request #49
Opened 2023-04-16 22:21 UTC by tsyk007

2023-04-18 05:46 UTC, Letto228 requested changes
Привет!
Оставил парочку комментариев, посмотри, пожалуйста. Буду ждать фидбека

2023-04-18 05:46 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +				color="{{ currentPageIndex === index ? 'primary' : '' }}"
Почему использовал интерполяцию?

2023-04-18 05:46 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +				(click)="onPage(index); $event.preventDefault()"
А зачем везде останавливал всплытие клика?

2023-04-18 05:46 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +	private get indexes() {
Давай порассуждаем над методом. Он вычисляет массив элементов - ок, но вызывается данный метод каждый раз, когда создается контекст - это не ок, т.к. на данный массив влияет только массив данных и кол-во элементов в чанке, если данные поля не изменяются, то и вычислять массив заново нет смысла.
Заметил еще, что в данному методу обращаемся в `next` и `back` методе

В целом, операция плевая, по этому производительность толком не пострадает, но я бы задумался над данным кейсом.

Еще я бы предложил более лаконичный метод создания массива через `Array.from` и метод `map`: 
```
const indexesLength = Math.ceil(this.appPaginationOf.length / this.appPaginationChankSize);

return Array.from({length: indexesLength}).map((_, index) => index);
```

2023-04-18 05:46 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +		) as T[];
По хорошим практикам - приведение должно использоваться для сужения типов. В твоем случае неопределенность есть у `this.appPaginationOf`, т.е. сузить нужно именно его типы, а дальше полноценно работать с массивом без приведения
```ts
return (this.appPaginationOf as T[]).slice(
			currentIndex * this.appPaginationChankSize,
			currentIndex * this.appPaginationChankSize + this.appPaginationChankSize,
);
```

И, конечно же, нужно добавить тип возвращаемого значения из метода

2023-04-18 05:46 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +	private get indexes() {
Так же нужно по хорошему добавить тип возращаемого значения

2023-04-20 07:52 UTC, tsyk007 commented on src/app/pages/products-list/products-list.component.html
> +				color="{{ currentPageIndex === index ? 'primary' : '' }}"
ну в данном примере это вроде не критично. Переделаю на binding

2023-04-20 07:58 UTC, tsyk007 commented on src/app/pages/products-list/products-list.component.html
> +				(click)="onPage(index); $event.preventDefault()"
да, это лишнее

2023-04-20 14:49 UTC, tsyk007 commented
вроде все поправил

2023-04-20 14:55 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +				color="{{ currentPageIndex === index ? 'primary' : '' }}"
Нет, не критично, будет работать одинаково хорошо, НО, если говорить про хорошие практики, чистоту и консистентность кода, то я не мог пройти мимо) На одной из ранних лекций обсуждали некоторое правило для упрощение применения данных механизмов и поддержания кода в чистоте: binding для привязывания свойств, а интерполяция для отображения контента на странице.

Придерживаться ли данного правила - выбор исключительно за тобой, я просто дополнительно решил подсветить, напомнить

2023-04-20 14:56 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.html
> +				color="{{ currentPageIndex === index ? 'primary' : '' }}"
Если есть желание пообсуждать - велком в ЛС Discord)

2023-04-20 15:00 UTC, tsyk007 commented on src/app/pages/products-list/products-list.component.html
> +				color="{{ currentPageIndex === index ? 'primary' : '' }}"
в целом я согласен, надо придерживаться

2023-04-20 15:38 UTC, Letto228 requested changes
Нашел баг - подсветил в комментарии, и накинул еще парочку, посмотри, пожалуйста

2023-04-20 15:38 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +	private buttonActiveColorValue: ThemePalette = 'primary';
Думаю, не стоит хранить данное свойство в классе директивы, т.к. для самой директивы оно бесполезно и контекст засоряет, да и вообще, она ничего не должна знать о кнопках, их выделении и т.д., эта логика остается в зоне ответсвенности компонента, который будет использовать данную директиву. Да и в целом такое решение лишает нас гибкости, а что если мы в другом месте захотим иначе выделять кнопку, другим color, то у нас так уже не получится - поменяем свойство в классе и оно изменится во всех местах, где применили директиву и завязались на свойстве контекста.

По этому давай выпилим, и оставим тернарник таким, какой он был в твоем перво варианте с интерполяцией `currentPageIndex === index ? 'primary' : ''` (но байдинг, конечно, стоит оставить, поменять нужно только сам тернарник)

2023-04-20 15:38 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +		if (updateIndexes) {
А может просто сделаем if с проверкой на изменение `appPaginationOf || appPaginationChankSize`? Избавимся от лишней переменной
```
if (appPaginationOf || appPaginationChankSize) {
    this.updateIndexes();
}
```

Или в этом есть сокральный смысл?

2023-04-20 15:38 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +		if (updateIndexes) {
А как думаешь, не стоит ли нам сбросить currentIndex?

И кажется, есть у нас бажок - перерисуется ли твое view при получении новых данных в инпуте `appPaginationOf `? Кажется, нет, новые данные придут и ничего не произойдет, только индексы пересчитаются, но новое view не создастся

2023-04-20 15:38 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +	updateIndexes() {
`private`?

2023-04-21 13:50 UTC, tsyk007 commented
Поправил. Про view немного не понял, но вроде все перерисовывается.

2023-04-23 08:37 UTC, Letto228 approved these changes
Апрув!

2023-04-23 08:37 UTC, closed without merging