feat: added filter pipe
Letto228/Angular-learnjs-200323 pull request #54
Opened 2023-04-18 10:23 UTC by BasankoSV

2023-04-20 16:02 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста

2023-04-20 16:02 UTC, Letto228 commented on src/app/shared/filter-by/filter-by.pipe.ts
> +		value: any,
Не нравится мне тут any, честно говоря, напрочь убиваем типизацию. Подскажи пожалуйста, по твоей логике, если ты будешь проверять строковое свойство, тот же 'name' например, то какие данные предполагается получать в аргумент `value` - любые, или тоже строку?

2023-04-20 16:02 UTC, Letto228 commented on src/app/shared/filter-by/filter-by.pipe.ts
> +		if (isNaN(value)) {
А как на счет строки `'123'`? Ее нужно сравнивать как строку, а получится, что мы сравним ее как число, обычным `===`, а не через `.startsWith`

2023-04-26 17:42 UTC, Letto228 approved these changes
Привет!
Все гуд - апрув. Оставил один не большой комментарий, но он совсем минорный, не будем из-за него держать МР

2023-04-26 17:42 UTC, Letto228 commented on src/app/shared/filter-by/filter-by.pipe.ts
> +					.startsWith(value.toString().toUpperCase()),
`value.toString()` - `toString()` излишен, мы выше проверили, что значение является строкой, и нет смысла строку перегонять в строку

2023-04-26 17:44 UTC, closed without merging

2023-04-27 04:19 UTC, BasankoSV commented on src/app/shared/filter-by/filter-by.pipe.ts
> +					.startsWith(value.toString().toUpperCase()),
Согласен! Торопился, не проверил! :-)